# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '*/5 * * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          layoutFile="TripXpert/Views/Shared/_Layout.cshtml";
          CURRENT_VERSION=$(grep -hnr "kendo.cdn" $layoutFile | head -1 |cut -d '/' -f 4)
          echo "Current release version from $layoutFile is $CURRENT_VERSION"
          
          LAST_RELEASE=$(curl -s https://api.github.com/repos/telerik/kendo-ui-core/releases | grep tag_name | head -n 1 |  cut -d '"' -f 4)
          echo "Last release version is $LAST_RELEASE"

          files=(TripXpert/TripXpert.csproj TripXpert/Views/Contact/Contact.cshtml TripXpert/Views/Destinations/DestinationDetails.cshtml TripXpert/Views/Destinations/Destinations.cshtml TripXpert/Views/Home/Index.cshtml TripXpert/Views/Shared/_Layout.cshtml TripXpert/packages.config TripXpert/service-worker.js)
          for file in ${files[@]}
            do
              sed -i "s/$CURRENT_VERSION/$LAST_RELEASE/g" $file
            done
          
          NEW_VERSION=$(grep -hnr "kendo.cdn" $layoutFile | head -1 |cut -d '/' -f 4)
          echo "New version set is $NEW_VERSION"
